---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.nginxImage }}
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: volume-nginx
        - name: get-article
          image: {{ .Values.nginx.getarticleImage }}
          env:
          - name: DBHOST
            valueFrom:
              configMapKeyRef:
                name: nginx-config
                key: dbhost
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: dbuser
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: dbpass
          - name: DBNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: dbname
          volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: volume-nginx
      volumes:
      - name: volume-nginx
        emptyDir: {}
