---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels }}
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: {{ .Values.labels }}
